import { create } from 'zustand';

const DUMMY_MATERIAL_ORDERS = [
  {
    id: 'ORD-2001',
    customerName: 'Rajesh Kumar',
    customerPhone: '9876543210',
    customerAddress: '24, 3rd Cross, Koramangala 5th Block, Bengaluru - 560095',
    date: '17 May 2026',
    time: '10:32 AM',
    status: 'new',
    paymentStatus: 'pending',
    paymentMethod: 'COD',
    subtotal: 4200,
    deliveryCharge: 150,
    total: 4350,
    type: 'material',
    items: [
      { id: 'i1', name: 'Portland Cement 50kg', qty: 6, price: 700, unit: 'bag' },
    ],
  },
  {
    id: 'ORD-2002',
    customerName: 'Suresh Nair',
    customerPhone: '9845012345',
    customerAddress: '12, Whitefield Main Rd, Whitefield, Bengaluru - 560066',
    date: '16 May 2026',
    time: '09:15 AM',
    status: 'accepted',
    paymentStatus: 'paid',
    paymentMethod: 'UPI',
    subtotal: 8750,
    deliveryCharge: 200,
    total: 8950,
    type: 'material',
    items: [
      { id: 'i2', name: 'Steel Rods 12mm', qty: 25, price: 350, unit: 'piece' },
    ],
  },
  {
    id: 'ORD-2003',
    customerName: 'Anita Sharma',
    customerPhone: '9741122334',
    customerAddress: '88, HSR Layout Sector 2, Bengaluru - 560102',
    date: '16 May 2026',
    time: '04:45 PM',
    status: 'out_for_delivery',
    paymentStatus: 'paid',
    paymentMethod: 'Online',
    subtotal: 6200,
    deliveryCharge: 100,
    total: 6300,
    type: 'material',
    items: [
      { id: 'i3', name: 'River Sand 1 Ton', qty: 1,   price: 3100, unit: 'ton'   },
      { id: 'i4', name: 'M-Sand Fine',      qty: 1,   price: 2400, unit: 'ton'   },
      { id: 'i5', name: 'Red Clay Bricks',  qty: 100, price: 7,    unit: 'piece' },
    ],
  },
  {
    id: 'ORD-2004',
    customerName: 'Vijay Reddy',
    customerPhone: '9632587410',
    customerAddress: '5, Indiranagar 100ft Rd, Bengaluru - 560038',
    date: '15 May 2026',
    time: '01:20 PM',
    status: 'delivered',
    paymentStatus: 'paid',
    paymentMethod: 'COD',
    subtotal: 3600,
    deliveryCharge: 0,
    total: 3600,
    type: 'material',
    items: [
      { id: 'i6', name: 'Portland Cement 50kg', qty: 2,   price: 700,  unit: 'bag' },
      { id: 'i7', name: '20mm Blue Metal',      qty: 1,   price: 1800, unit: 'ton' },
      { id: 'i8', name: 'River Sand 1 Ton',     qty: 0.3, price: 3100, unit: 'ton' },
    ],
  },
  {
    id: 'ORD-2005',
    customerName: 'Meera Pillai',
    customerPhone: '9988776655',
    customerAddress: '33, JP Nagar 6th Phase, Bengaluru - 560078',
    date: '15 May 2026',
    time: '11:05 AM',
    status: 'cancelled',
    paymentStatus: 'refunded',
    paymentMethod: 'UPI',
    subtotal: 3100,
    deliveryCharge: 150,
    total: 3250,
    type: 'material',
    items: [
      { id: 'i9', name: 'River Sand 1 Ton', qty: 1, price: 3100, unit: 'ton' },
    ],
  },
  {
    id: 'ORD-2006',
    customerName: 'Kiran Bhat',
    customerPhone: '9123456789',
    customerAddress: '7, Malleshwaram 8th Cross, Bengaluru - 560003',
    date: '14 May 2026',
    time: '03:00 PM',
    status: 'new',
    paymentStatus: 'pending',
    paymentMethod: 'COD',
    subtotal: 5600,
    deliveryCharge: 200,
    total: 5800,
    type: 'material',
    items: [
      { id: 'i10', name: 'Steel Rods 12mm',      qty: 10, price: 350, unit: 'piece' },
      { id: 'i11', name: 'Portland Cement 50kg', qty: 3,  price: 700, unit: 'bag'   },
    ],
  },
];

const DUMMY_RENTAL_ORDERS = [
  {
    id: 'RNT-1001',
    customerName: 'Arjun Shetty',
    customerPhone: '9876501234',
    customerAddress: '14, Banashankari 2nd Stage, Bengaluru - 560070',
    date: '17 May 2026',
    time: '08:00 AM',
    status: 'new',
    paymentStatus: 'pending',
    paymentMethod: 'COD',
    type: 'rental',
    depositAmount: 5000,
    depositStatus: 'pending',
    startDate: '18 May 2026',
    endDate: '25 May 2026',
    durationDays: 7,
    subtotal: 10500,
    deliveryCharge: 300,
    total: 10800,
    items: [
      {
        id: 'ri1',
        name: 'Concrete Mixer 500L',
        qty: 1,
        pricePerDay: 1500,
        days: 7,
        unit: 'unit',
        deposit: 5000,
      },
    ],
  },
  {
    id: 'RNT-1002',
    customerName: 'Deepa Menon',
    customerPhone: '9845098765',
    customerAddress: '56, Jayanagar 4th Block, Bengaluru - 560041',
    date: '16 May 2026',
    time: '11:30 AM',
    status: 'active',
    paymentStatus: 'paid',
    paymentMethod: 'UPI',
    type: 'rental',
    depositAmount: 8000,
    depositStatus: 'collected',
    startDate: '16 May 2026',
    endDate: '22 May 2026',
    durationDays: 6,
    subtotal: 7200,
    deliveryCharge: 200,
    total: 7400,
    items: [
      {
        id: 'ri2',
        name: 'Scaffolding Set (20ft)',
        qty: 2,
        pricePerDay: 600,
        days: 6,
        unit: 'set',
        deposit: 4000,
      },
    ],
  },
  {
    id: 'RNT-1003',
    customerName: 'Praveen Kumar',
    customerPhone: '9632147850',
    customerAddress: '3, Electronic City Phase 1, Bengaluru - 560100',
    date: '15 May 2026',
    time: '02:00 PM',
    status: 'overdue',
    paymentStatus: 'paid',
    paymentMethod: 'Online',
    type: 'rental',
    depositAmount: 3000,
    depositStatus: 'collected',
    startDate: '10 May 2026',
    endDate: '14 May 2026',
    durationDays: 4,
    subtotal: 4000,
    deliveryCharge: 150,
    total: 4150,
    items: [
      {
        id: 'ri3',
        name: 'Plate Compactor',
        qty: 1,
        pricePerDay: 1000,
        days: 4,
        unit: 'unit',
        deposit: 3000,
      },
    ],
  },
  {
    id: 'RNT-1004',
    customerName: 'Lakshmi Nair',
    customerPhone: '9741236985',
    customerAddress: '22, Yelahanka New Town, Bengaluru - 560064',
    date: '14 May 2026',
    time: '09:45 AM',
    status: 'returned',
    paymentStatus: 'paid',
    paymentMethod: 'UPI',
    type: 'rental',
    depositAmount: 6000,
    depositStatus: 'refunded',
    startDate: '10 May 2026',
    endDate: '13 May 2026',
    durationDays: 3,
    subtotal: 5400,
    deliveryCharge: 200,
    total: 5600,
    items: [
      {
        id: 'ri4',
        name: 'Tower Light 1000W',
        qty: 2,
        pricePerDay: 900,
        days: 3,
        unit: 'unit',
        deposit: 3000,
      },
    ],
  },
  {
    id: 'RNT-1005',
    customerName: 'Harish Gowda',
    customerPhone: '9988001122',
    customerAddress: '8, Hebbal Ring Rd, Bengaluru - 560024',
    date: '13 May 2026',
    time: '04:15 PM',
    status: 'cancelled',
    paymentStatus: 'refunded',
    paymentMethod: 'COD',
    type: 'rental',
    depositAmount: 4000,
    depositStatus: 'refunded',
    startDate: '15 May 2026',
    endDate: '18 May 2026',
    durationDays: 3,
    subtotal: 3600,
    deliveryCharge: 0,
    total: 3600,
    items: [
      {
        id: 'ri5',
        name: 'Concrete Vibrator',
        qty: 1,
        pricePerDay: 1200,
        days: 3,
        unit: 'unit',
        deposit: 4000,
      },
    ],
  },
  {
    id: 'RNT-1006',
    customerName: 'Sowmya Rao',
    customerPhone: '9123004567',
    customerAddress: '91, Rajajinagar 1st Block, Bengaluru - 560010',
    date: '12 May 2026',
    time: '10:00 AM',
    status: 'new',
    paymentStatus: 'pending',
    paymentMethod: 'COD',
    type: 'rental',
    depositAmount: 7000,
    depositStatus: 'pending',
    startDate: '20 May 2026',
    endDate: '27 May 2026',
    durationDays: 7,
    subtotal: 8400,
    deliveryCharge: 350,
    total: 8750,
    items: [
      {
        id: 'ri6',
        name: 'Boom Lift 12m',
        qty: 1,
        pricePerDay: 1200,
        days: 7,
        unit: 'unit',
        deposit: 7000,
      },
    ],
  },
];

const DUMMY_INVENTORY = [
  { id: '1', name: 'Portland Cement 50kg', stock: 3,  price: 700,  type: 'material', lowStock: true  },
  { id: '2', name: 'Steel Rods 12mm',      stock: 40, price: 350,  type: 'material', lowStock: false },
  { id: '3', name: 'Concrete Mixer',       stock: 2,  price: 1500, type: 'rental',   lowStock: true  },
  { id: '4', name: 'Scaffolding Set',      stock: 5,  price: 2200, type: 'rental',   lowStock: false },
  { id: '5', name: 'River Sand 1 Ton',     stock: 8,  price: 3100, type: 'material', lowStock: false },
];

const DUMMY_CHART = {
  day:   [2, 4, 3, 6, 5, 8, 7],
  week:  [18, 24, 20, 30, 28, 35, 32],
  month: [80, 95, 110, 130, 120, 150, 145],
};

const useVendorStore = create((set, get) => ({
  vendor: {
    name:          'Nithin Hegde',
    shopName:      'Hegde Traders',
    walletBalance: 24500,
    monthEarnings: 68200,
    growth:        '+12%',
  },

  materialOrders: DUMMY_MATERIAL_ORDERS,
  rentalOrders:   DUMMY_RENTAL_ORDERS,
  inventory:      DUMMY_INVENTORY,
  chartData:      DUMMY_CHART,

  kpi: {
    newOrders:       12,
    pendingDelivery:  4,
    activeListings:  18,
    lowStockItems:    3,
  },

  earningsFilter: 'week',
  setEarningsFilter: (filter) => set({ earningsFilter: filter }),

  getFilteredOrders: (mode) => {
    return mode === 'materials'
      ? get().materialOrders
      : get().rentalOrders;
  },

  getFilteredInventory: (mode) => {
    const type = mode === 'materials' ? 'material' : 'rental';
    return get().inventory.filter((i) => i.type === type);
  },
}));

export default useVendorStore;