const express = require('express')
const router = express.Router()

router.use('/auth', require('./auth.routes'))
router.use('/dashboard', require('./dashboard.routes'))
router.use('/admins', require('./admin.routes'))
router.use('/roles', require('./role.routes'))
router.use('/customers', require('./customer.routes'))
router.use('/workers', require('./worker.routes'))
router.use('/vendors', require('./vendor.routes'))
router.use('/bookings', require('./booking.routes'))
router.use('/orders', require('./order.routes'))
router.use('/services', require('./service.routes'))
router.use('/finance', require('./finance.routes'))
router.use('/wallets', require('./wallet.routes'))
router.use('/payments', require('./payment.routes'))
router.use('/notifications', require('./notification.routes'))
router.use('/complaints', require('./complaint.routes'))
router.use('/reviews', require('./review.routes'))
router.use('/promotions', require('./promotion.routes'))
router.use('/content', require('./content.routes'))
router.use('/analytics', require('./analytics.routes'))
router.use('/audit-logs', require('./auditLog.routes'))
router.use('/materials', require('./material.routes'))
router.use('/rentals', require('./rental.routes'))
router.use('/inventory', require('./inventory.routes'))
router.use('/business-partners', require('./businessPartner.routes'))
router.use('/pricing', require('./pricing.routes'))
router.use('/maps', require('./map.routes'))

module.exports = router